In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [2]:
# 다항식으로 변환한 단항식 생성, [[0,1],[2,3]]의 2X2 행렬 생성
X = np.arange(4).reshape(2,2)
print('일차 단항식 계수 feature:\n',X )

일차 단항식 계수 feature:
 [[0 1]
 [2 3]]


In [3]:
# degree = 2 인 2차 다항식으로 변환하기 위해 PolynomialFeatures를 이용하여 변환
poly = PolynomialFeatures(degree=2, include_bias=False)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 2차 다항식 계수 feature with include_bias False:\n', poly_ftr)

변환된 2차 다항식 계수 feature with include_bias False:
 [[0. 1. 0. 0. 1.]
 [2. 3. 4. 6. 9.]]


In [4]:
poly = PolynomialFeatures(degree=2, include_bias=True)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 2차 다항식 계수 feature with include_bias False:\n', poly_ftr)

변환된 2차 다항식 계수 feature with include_bias False:
 [[1. 0. 1. 0. 0. 1.]
 [1. 2. 3. 4. 6. 9.]]
