In [1]:
import numpy

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 17, 23, 45, 255])

In [3]:
array1

array([  2,   3,   5,   7,  11,  17,  23,  45, 255])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(9,)

In [6]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
array2.shape

(3, 4)

### *size*는 몇개의 요소가 들어있는지에 대해서
### *len()*은 리스트의 길이, 즉 가장 바깥 리스트의 길이를 알려준다

In [9]:
array1.size

9

In [10]:
array2.size

12

In [11]:
len(array1)

9

In [12]:
len(array2)

3

### 균일한 값으로 생성

In [13]:
array3 = numpy.full(6,7)

print(array3)

[7 7 7 7 7 7]


In [14]:
array4 = numpy.zeros(6, dtype=int)
print(array4)

[0 0 0 0 0 0]


In [15]:
array5 = numpy.ones(6, dtype=int)
print(array5)

[1 1 1 1 1 1]


In [16]:
array6 = numpy.random.random(6)
print(array6)

[0.76454534 0.43392544 0.01756442 0.32055286 0.70370852 0.56383319]


In [17]:
array7 = numpy.arange(3, 20, 3)
print(array7)

[ 3  6  9 12 15 18]


## 인덱싱, 슬라이싱

In [20]:
array8 = numpy.array([2, 3, 5, 7, 11, 17, 23, 45, 255])
print(array8[0])
print(array8[5])

2
17


In [21]:
array8[-1]

255

In [22]:
array8[[1, 3, 4]]

array([ 3,  7, 11])

In [23]:
array8[2:5]

array([ 5,  7, 11])

In [24]:
array8[2:8:3]

array([ 5, 17])