In [1]:
import numpy as np

In [2]:
array1 = np.array([2, 3, 5, 6, 8, 11, 23, 55])

In [3]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True])

In [4]:
array1 % 2 == 0

array([ True, False, False,  True,  True, False, False, False])

In [5]:
booleans = np.array([True, True, True, False, True, True, False])

In [6]:
np.where(booleans)

(array([0, 1, 2, 4, 5], dtype=int64),)

In [7]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True])

In [9]:
filter = np.where(array1 > 4)
filter

(array([2, 3, 4, 5, 6, 7], dtype=int64),)

In [10]:
array1[filter]

array([ 5,  6,  8, 11, 23, 55])

### 최대 최소값

In [11]:
print(array1.max())
print(array1.min())

55
2


### 평균값

In [12]:
print(array1.mean())

14.125


### 중앙값

In [13]:
print(np.median(array1))

7.0


### 표준편차, 분산

In [15]:
print(array1.std()) # 표준 편차
print(array1.var()) # 분산

16.6466025062173
277.109375
