In [12]:
import numpy as np

In [13]:
arr = [[1, 3, 5], [2, 4, 8]]
np_arr =  np.array(arr)

In [20]:
arr = np.arange(2, 21, 2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
arr.shape

(10,)

In [22]:
np.reshape(arr, (5, 2))

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [23]:
arr2 = np.arange(0, 100, 1)

In [26]:
s_arr = np.reshape(arr2, (4, 25))
s_arr.shape

(4, 25)

In [28]:
np.hstack(s_arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
np.vstack(arr)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20]])